<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fQ2_UIE' shared service.

return $this->privates['.service_locator.fQ2_UIE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['article' => function (): \App\Entity\Article {
    return ($this->privates['.errored..service_locator.fQ2_UIE.App\Entity\Article'] ?? $this->load('getArticle3Service.php'));
}, 'em' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}]);
