<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.fQ2_UIE.App\Entity\Article' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.fQ2_UIE": it references class "App\\Entity\\Article" but no such service exists.');
